name: Fly Deploy NodeBB Production
on:
  push:
    branches: ["main", "career-model/dev"]
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Create NodeBB config.json from GitHub secrets
        env:
          CONFIG: ${{ secrets.NODEBB_CONFIG }}
        run: |
          echo "$CONFIG" > config.json
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
